sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.1
      env: DEPS=--prefer-lowest

before_install:
  - composer selfupdate --no-interaction

install:
  - travis_retry composer update -n $DEPS

script:
  - ./vendor/bin/phpunit -c "./test/phpunit.xml"

notifications:
  email: false
